define(['foliage', 
	'overview', 
	'md!foliage/readme.md',
	'md!blossom/readme.md',
	'md!twig/README.md',
        'md!epiphyte/README.md',
	'md!phloem/README.md',
	'md!papyrus/README.md'
       ], 
       function(f, 
		overview, 
		foliage,
                blossom,
		twig,
	        epiphyte,
		phloem,
		papyrus) {
    return f.div({'class': 'container'},
		 f.div({'class': 'row'},
		       f.div({'class': 'span12'},
			     f.div({'class': 'row'},
				   f.ul(
				       {'class': 'thumbnails'},
				       overview(twig, 'twig'),
				       overview(foliage, 'foliage'),
                                       overview(blossom, 'blossom'),
				       overview(phloem, 'phloem'),
				       overview(epiphyte, 'epiphyte'),
				       overview(papyrus, 'papyrus'))))));
})
